// Строки ДОЛЖНЫ совпадать с enum PlcNodeType (Kotlin)
export const NODE_TYPES = [
    "CONST_BOOL",
    "CONST_INT",
    "DIGITAL_IN",
    "DIGITAL_OUT",
    "AND2",
    "OR2",
    "NOT",
    "SR",
    "TON",
    "TOFF",
    "R_TRIG",
    "F_TRIG",
    "AI_IN",
    "COMPARE_GT",
    "COMPARE_LT",
    "PWM_OUT",
    "MUX2",
    "TP",
    "HYST",
    "SCALE",
    "ADD",
    "LIMIT",
    "PID",
    "ANALOG_AVG",
    "RAMP",
    "LOG",
    "AO",
    "CTU",
    "CTD",
    "CTUD",
    "WINDOW_CHECK",
    "SAFE_OUTPUT",
    "ALARM_GEN",
    "ALARM_LATCH",
    "HEARTBEAT",
    "MEM_BOOL",
    "MEM_INT",
    "MEM_REAL",
    "FILTER_AVG",
    "MATH_OP",
    "CONST_FLOAT",
] as const

export type NodeType = (typeof NODE_TYPES)[number]

// (опционально) подписи
export const NODE_LABEL: Record<NodeType, string> = {
    CONST_BOOL: "CONST_BOOL (константа bool)",
    CONST_INT: "CONST_INT (константа int)",
    CONST_FLOAT: "CONST_FLOAT (константа float)",
    DIGITAL_IN: "DIGITAL_IN (дискретный вход)",
    DIGITAL_OUT: "DIGITAL_OUT (дискретный выход)",
    AND2: "AND2 (логическое И)",
    OR2: "OR2 (логическое ИЛИ)",
    NOT: "NOT (инвертор)",
    SR: "SR (защёлка Set/Reset)",
    TON: "TON (таймер на включение)",
    TOFF: "TOFF (таймер на выключение)",
    TP: "TP (одноимпульсный таймер)",
    R_TRIG: "R_TRIG (фронт 0→1)",
    F_TRIG: "F_TRIG (спад 1→0)",
    AI_IN: "AI_IN (аналоговый вход)",
    COMPARE_GT: "COMPARE_GT (A > B)",
    COMPARE_LT: "COMPARE_LT (A < B)",
    PWM_OUT: "PWM_OUT (ШИМ выход)",
    MUX2: "MUX2 (селектор)",
    HYST: "HYST (гистерезис)",
    SCALE: "SCALE (y=a*x+b)",
    ADD: "ADD (A+B float)",
    LIMIT: "LIMIT (clamp min/max)",
    PID: "PID (регулятор)",
    ANALOG_AVG: "ANALOG_AVG (сглаживание)",
    RAMP: "RAMP (ограничение скорости)",
    LOG: "LOG (логирование)",
    AO: "AO (аналоговый выход)",
    CTU: "CTU (счётчик вверх)",
    CTD: "CTD (счётчик вниз)",
    CTUD: "CTUD (счётчик up/down)",
    WINDOW_CHECK: "WINDOW_CHECK (окно)",
    SAFE_OUTPUT: "SAFE_OUTPUT (безопасный выход)",
    ALARM_GEN: "ALARM_GEN (авария)",
    ALARM_LATCH: "ALARM_LATCH (авария latch)",
    HEARTBEAT: "HEARTBEAT (сердцебиение)",
    MEM_BOOL: "MEM_BOOL (память bool)",
    MEM_INT: "MEM_INT (память int)",
    MEM_REAL: "MEM_REAL (память real)",
    FILTER_AVG: "FILTER_AVG (эксп. фильтр)",
    MATH_OP: "MATH_OP (+-*/)",
}
